import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * English sidebar. The tree is generated from the docs/ folder for now;
 * switch to explicit entries when the Sparrow Sync documentation grows.
 * Keep sidebars/zh-hans.ts structurally in sync with this file.
 */
const sidebars: SidebarsConfig = {
  docs: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
