import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * 中文侧边栏。目前同样由 docs/ 目录自动生成；文档 id 与英文版一致,
 * 中文内容放在 i18n/zh-Hans/docusaurus-plugin-content-docs/current/ 下,
 * 缺失的页面会回退到英文原文。结构上请与 sidebars/en.ts 保持同步。
 */
const sidebars: SidebarsConfig = {
  docs: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
